config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :users
  resources 'items'
  resources 'carts', only: [:show]
  resources 'shopping_sessions', only: [:new, :destroy]
  resources 'teams', only: [:index]
  resources 'orders', only: [:create, :index]
  resources 'users', only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :user
  has_many :shopping_sessions
  has_many :items, through: :shopping_sessions
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :shopping_sessions
  has_many :carts, through: :shopping_sessions

  belongs_to :category

  has_many :order_items
  has_many :orders, through: :order_items

  validates :title,
            presence: true,
            length: {in: 3..25}

  validates :description,
            length: {maximum: 1500}
  validates :image_url,
            presence: true
  validates :price,
            presence: true,
            numericality: { greater_than: 0, less_than: 100 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items
  has_many :items, through: :order_items

  after_create :order_email_send, :order_admin_send

  def order_email_send
    OrderMailer.order_email(self).deliver_now
  end

  def order_admin_send
    AdminMailer.order_email(self).deliver_now
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/shopping_session.rb
class ShoppingSession < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  before_action :create_session_cart

  # If session cart does not already exist then create it
  def create_session_cart
    if user_signed_in? && !current_user.cart
      session['cart'] = Cart.create(user_id: current_user.id)
    end
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      flash[:notice] = 'Vous devez être connecté pour accéder à cette page.'
      redirect_to new_user_session_path
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!

  def show
    # Get user's cart's items to pass it to the view
    @items = current_user.cart.items

    # Calculate total cart price to pass it to the view
    @cart_price = helpers.calculate_total_cart_price(@items)

    # Count total number of items to pass is to the view
    @items_count = @items.count
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!, except: [:index, :show]
  before_action :create_session_cart

  def index
    @items = Item.all
    @categories = Category.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.create
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
  end

  def update
    @item = Item.find(params[:id])
    @item.update
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ApplicationHelper

  before_action :create_session_cart

  # Show all user's passed orders and their orders
  def index
    @orders = current_user.orders
    @items = Item.all
  end

  def create
    # Get carts informations
    @cart = current_user.cart

    # Get total cart price
    @cart_price = helpers.calculate_total_cart_price(@cart.items)

    # Amount in cents
    @amount = @cart_price.to_i * 100

    customer = Stripe::Customer.create(
        {
            email: params[:stripeEmail],
            source: params[:stripeToken],
        })

    charge = Stripe::Charge.create(
        {
            customer: customer.id,
            amount: @amount,
            description: 'Rails Stripe customer',
            currency: 'EUR',
        })

    # Save cart's data as an order
    @order = Order.create!(stripe_customer_id: customer.id, user_id: current_user.id)

    # Save cart's items as order_items
    current_user.cart.items.each do |item|
      @order_items = OrderItem.create!(
          quantity: 1, # TODO : Replace this by item.quantity once the property will be added to the items table
          total_price: calculate_total_cart_price(current_user.cart.items),
          order_id: @order.id,
          item_id: item.id
      )
    end

    # Empty user's cart
    current_user.cart.items.destroy_all

    # Redirect and display success message
    flash[:success] = "Miaaaaouh ! Votre commande à été acceptée et vous sera prochainement envoyée par email."
    redirect_to root_path
  end

end

app/controllers/shopping_sessions_controller.rb
class ShoppingSessionsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!

  def new
    # Get user's item
    @item = Item.find(params[:id])

    # Add the item to user's cart
    unless current_user.cart.items.include?(@item)
      current_user.cart.items << @item
      current_user.save
    end

    flash[:success] = "Le produit a bien été ajouté au panier"

    redirect_back(fallback_location: root_path)
  end

  def destroy
    # Find the item to remove
    @item = Item.find(params[:id])

    # Remove the item from Cart's item' list if it is present
    if current_user.cart.items.include?(@item)
      current_user.cart.items.delete(@item)
    end

    flash[:error] = "Le produit a bien été retiré du panier"

    redirect_back(fallback_location: root_path)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(params.require(:user).permit(
        :first_name, :last_name, :description, :address, :zipcode)
    )
    redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
    when 'notice' then "alert-info"
    when 'success' then "alert-success"
    when 'error' then "alert-danger"
    when 'alert' then "alert-warning"
    else
      "alert-info"
    end
  end

  # Calculate cart price
  def calculate_total_cart_price(items)
    @cart_price = 0

    items.each do |item|
      @cart_price += item.price
    end

    @cart_price
  end

  def is_item_in_cart?(item)
    user_signed_in? && current_user.cart && current_user.cart.items.include?(item) ? true : false
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/carts/_stripe_form.html.erb
<%= form_tag orders_path do %>
  <article>
    <!-- Error Message -->
    <% if flash[:error].present? %>
      <div class="alert mt-3 alert-danger alert-dismissable fade show" id="error_explanation" role="alert">
        <%= flash[:error] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Payer votre commande"
          data-amount="<%= cart_price * 100 %>"
          data-locale="fr"
          data-currency="eur"
          data-country="FR"
          data-label="Cliquer pour payer <%= cart_price %> €"
          data-image="https://image.flaticon.com/icons/svg/616/616430.svg">
  </script>
<% end %>

app/views/carts/show.html.erb
<!-- Page Title-->
<h1 class="display-4-selection text-center my-5">Votre panier</h1>

<div class="row justify-content-around mb-3">
  <!-- If cart is empty-->
  <% if !current_user.cart.items.first %>
    <div class="row flex-column justify-content-center mb-5">
      <h2 class="text-center">Oups ! On dirait que votre panier est vide... <br />Ajoutez des photos sans plus attendre !</h2>
      <%= image_tag 'empty_cart.svg', size: "400", class: "mx-auto" %>
      <%= link_to items_path, style: "text-decoration:none" do %>
        <button class="btn btn-primary btn-block p-3 font-weight-bold" type="button"><i class="fas fa-shopping-basket mr-3"></i>Choisir des photos</button>
      <% end %>
    </div>
  <% else %>
    <!-- Items list -->
    <div class="col-lg-6">
      <% @items.sort_by(&:price).each do |item| %>
        <div class="row">
          <div class="card card-cart align-items-center mb-3">
            <div class="row align-items-center">
              <div class="col-lg-4">
                <a href="<%= item_path(item.id) %>">
                  <div class="cart-card-cat-img" style="background-image:url(<%= item.image_url %>)"></div>
                </a>
              </div>
              <div class="col-lg-8">
                <div class="card-body">
<!--                  <a href="<%#= shopping_session_path(item.id) %>" data-method="DELETE" class="close">&times;</a>-->
                  <%= button_to shopping_session_path(item.id), method: :delete, class: "close" do%>&times;<% end %>
                  <div class="row align-items-center">
                    <div class="col">
                      <h5 class="card-title"><%= item.title %></h5>
                      <!-- ---------------------------- TODO: Rajouter item.category --------------------------- -->
                      <small class="text-muted">Chat..pardeur</small>
                    </div>
                    <div class="col">
                      <p class="h3 text-right"><%= item.price %>€</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Cart total amount -->
    <div class="col-lg-4">
      <h2 class="text-center mb-5">Total de votre panier (<%= @items_count %>)</h2>

      <div class="row ml-5">
        <p class="mb-3"><i class="fas fa-check mr-3"></i>Aucun frais de ports</p>
        <p class="mb-3"><i class="fas fa-check mr-3"></i>Envoi instantané par email</p>
        <p class="mb-3"><i class="fas fa-check mr-3"></i>Satisfait mais pas remboursé</p>
      </div>
      <!-- Divider -->
      <hr class="mt-5"/>

      <!-- Shipping price-->
      <div class="row">
        <div class="col text-left"><p class="font-weight-bold">Livraison</p></div>
        <div class="col text-right">Gratuite</div>
      </div>

      <!-- Total Products Price -->
      <div class="row">
        <div class="col text-left"><p class="font-weight-bold">Sous-total</p></div>
        <div class="col text-right"><%= @cart_price %>€</div>
      </div>

      <!-- Create order Button -->
      <div class="row justify-content-center">
        <%= render 'carts/stripe_form', {cart_price: @cart_price} %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/index.html.erb
<!-- Page Title-->
<h2 class="display-4-selection text-center mb-5">Notre sélection du jour</h2>

<!-- Page Content -->
<div class="row justify-content-center">

  <!-- Sort by categories -->
  <%= render 'layouts/sorting' %>

  <div class="col-lg-10 mt-5">
    <%= render 'layouts/cards' %>
  </div>

</div>

app/views/items/new.html.erb
Test

app/views/items/show.html.erb
<div class="row align-items-center m-auto">

  <div class="col-lg-6 container text-center align-middle mt-5 py-lg-5">
    <%= image_tag @item.image_url, alt: 'cat picture', class: 'rounded border border-primary'%>
  </div>

  <div class="col-lg-6 container mt-5 py-5">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title"><%= @item.title %></h3>
        <h6 class="card-subtitle mb-2 text-muted">Race : <%= @item.title %></h6>
        <p class="card-text">
          <%= @item.description %><br/>
        </p>
      </div>
    </div>
    <div class="row mt-3 mx-3 justify-content-between">
      <h4>Prix : <%= @item.price %> €</h4>
      <% if is_item_in_cart?(@item) %>
        <!-- Button Remove item from cart-->
        <%= button_to shopping_session_path(@item.id), method: :delete, class: "btn btn-outline-danger" do%>
          <i class="fas fa-cart-arrow-down"></i> Retirer du panier
        <% end %>
      <% else %>
        <!-- Button add item to cart -->
        <a href="<%= new_shopping_session_path(id: @item.id) %>" class="btn btn-primary"><i class="fas fa-cart-arrow-down"></i> Ajouter au panier</a>
      <% end %>
    </div>
  </div>

</div>

app/views/layouts/_card.html.erb
<!-- Card -->
<div class="row row-cols-1 row-cols-md-2">
  <% 8.times do %>

    <div class="col-12 col-md-6 col-lg-4 mb-4">
      <div class="card">
        <img src="https://image.winudf.com/v2/image/Y29tLkN1dGVraXR0eS5hbGlmZHJvaWRfc2NyZWVuXzFfMTUwNjQ1NjUyM18wMjc/screen-1.jpg?h=355&fakeurl=1&type=.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <div class="row">
            <div class="col-8">
              <!-- Name + Breed-->
              <h5 class="card-title">Cat name <span class="badge badge-secondary">Persan</span></h5>
            </div>
            <div class="col-4">
              <!-- Notation -->
              <p class="card-text text-center"><small class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</small></p>
            </div>
          </div>
          <!-- Description -->
          <p class="card-text"><%= truncate("Some quick example text to build on the card title and make up the bulk of the card's content.", :length => 80) %></p>
          <!-- Price -->
          <p class="card-text h4 text-center">199.90€</p>
        </div>
        <div class="card-footer text-center">
          <a href="#" class="btn btn-primary"><i class="fas fa-cart-arrow-down"></i> Ajouter au panier</a>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/_cards.html.erb
<!-- Card -->
<div class="row row-cols-1 row-cols-md-2">
  <% @items.each do |item| %>
    <div class="col-12 col-md-6 col-lg-4 mb-4">
      <div class="card h-100">
        <a href="<%= item_path(item.id) %>">
          <img src="<%= item.image_url %>" class="card-img-top" alt="...">
        </a>
        <div class="card-body">
          <div class="row">
            <div class="col-8">
              <!-- Name + Breed-->
              <h5 class="card-title"><%= item.title %> <span class="badge badge-secondary"><%= item.category.title %></span></h5>
            </div>
            <div class="col-4">
              <!-- Notation -->
              <p class="card-text text-center"><small class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</small></p>
            </div>
          </div>
          <!-- Description -->
          <p class="card-text"><%= truncate(item.description, :length => 150) %></p>
          <!-- Price -->
          <p class="card-text h4 text-center"><%= item.price %>€</p>
        </div>
        <div class="card-footer text-center">
          <% if is_item_in_cart?(item) %>
            <!-- Button Remove item from cart-->
<!--            <a href="<%#= shopping_session_path(item.id) %>" data-method="DELETE" class="btn btn-outline-danger"><i class="fas fa-cart-arrow-down"></i> Retirer du panier</a>-->
            <%= button_to shopping_session_path(item.id), method: :delete, class: "btn btn-outline-danger" do%>
              <i class="fas fa-cart-arrow-down"></i> Retirer du panier
            <% end %>
          <% else %>
            <!-- Button add item to cart -->
            <a href="<%= new_shopping_session_path(id: item.id) %>" class="btn btn-primary"><i class="fas fa-cart-arrow-down"></i> Ajouter au panier</a>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<!-- Flash Messages -->
<% flash.each do |type, msg| %>
  <div class="alert mt-3 <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer-->
<footer class="py-5 bg-primary">
  <div class="container-fluid">
    <p class="m-0 text-center text-white">
      Développé avec &#10084;&#65039; par
      <a href="//github.com/Julio-Bento-Diddy-Lara-Detsou-team/The-not-loosing-a-joker-because-of-a-kitty-Project" target="_blank" class="text-light">
      The Covid-Killers-Team</a>	&#128298;
      pour <a href="//www.thehackingproject.org/fr" target="_blank" class="text-light">THP</a>
    </p>
  </div>
</footer>

app/views/layouts/_jumbotron.html.erb
<!-- JUMBOTRON -->
<section>
  <div class="jumbotron jumbotron-fluid">
    <div class="container text-center text-light">
      <h1 class="display-4">Kitty Sweety,</h1>
      <h2 class="h3 mb-3">l'appli de photos de chatons trop <em>trendy</em> !</h2>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>"> Kitty Sweety </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item px-3 h5">
          <%= link_to "La Team ", teams_path, class: "nav-link", role: "button" %>
        </li>
        <!-- If user connected-->
        <% if user_signed_in? %>
          <% if current_user.cart %>
            <% if current_user.cart.items.any? %>
              <li class="nav-item">
                <a href="<%= cart_path(current_user.cart.id) %>" class="btn btn-success mr-2"><i class="fas fa-cart-arrow-down fa-md"></i></a>
              </li>
              <% else %>
              <li class="nav-item">
                <a href="<%= cart_path(current_user.cart.id) %>" class="btn btn-outline-success mr-2"><i class="fas fa-shopping-cart fa-md"></i></a>
              </li>
            <% end %>
          <% end %>
          <li class="nav-item dropdown">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Ma session 🐱
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mes commandes", orders_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>              
              <%= link_to "Modifier mes infos", user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <!-- If user not connected -->
          <li class="btn-group">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Connexion/Inscription 🐱</button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Se connecter", new_user_session_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to "S'inscrire", new_user_registration_path, class: 'dropdown-item' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice_messages.html.erb
<!-- Flash Messages -->
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    &#128075; <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
<% end %>

app/views/layouts/_sorting.html.erb
<!-- Sort by categories -->
<div class="col-6">
  <div class="row justify-content-around">
    <% @categories.each do |category| %>
      <p id=<%= category.title.split.join.downcase %> class="btn btn-outline-primary"><%= category.title %></p>
    <% end %>
  </div>
</div>

app/views/layouts/_user.html.erb
<!--------------------------------Encart Devise User-------------------------------------->
<div class="container mt-a pt-5">
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
      <li>Voici ton email : <%= current_user.email %></li>
      <li><%= link_to "Editer email / mot de passe", edit_user_registration_path %></li>
    <% else %>
      <li><%= link_to "Se connecter'", new_user_session_path %></li>
      <li><%= link_to "S'inscrire", new_user_registration_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>	&#128008; Kitty Sweety</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon -->
  <!--    <link rel="icon" href="<%#= image_path 'logo.png' %>" />-->
  <!-- Fontawesome Icons CDN-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  <!-- Custom CSS -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <%= render "layouts/navbar" %>
</header>

<main>
  <% if controller_name === 'items' && action_name === 'index' %>
    <%= render "layouts/jumbotron" %>
  <% end %>

  <div class="container">
    <%= render "layouts/flash_messages" %>
    <%= yield %>
  </div>
</main>

<%= render "layouts/footer" %>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<!-- Optional JavaScript -->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning': true %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<!-- Page Title-->
<h2 class="display-4-selection text-center mb-5">Historiques de vos commandes</h2>

<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <!-- Display orders -->
      <% active = true %>

      <% @orders.each do |order| %>
        <a class="list-group-item list-group-item-action <%= "active" if active %>" id="list-settings-list" data-toggle="list" href="#list-<%= order.id %>" role="tab" aria-controls="<%= order.id %>">
          <span class="h6 mr-3">Commande :</span> #<%= order.id %> <br />
          <span class="h6 mr-3">Date :</span> <%= order.created_at.strftime("%d/%m/%Y %H:%M") %> <br />
          <span class="h6 mr-3">Montant : </span><%= calculate_total_cart_price(order.items) %> € <br />
          <span class="h6 mr-3">Nombre de photos : </span><%= order.items.count %> €
        </a>
        <% active = false %>
      <% end %>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <!-- Display order_items -->
      <% active_item = true %>

      <% @orders.each do |order| %>
        <div class="tab-pane fade <%= "active show" if active_item %>" id="list-<%= order.id %>" role="tabpanel" aria-labelledby="list-<%= order.id %>-list">
          <% order.order_items.each do |order_item| %>
            <% @item = @items.find(order_item.item_id) %>
            <ul style="list-style: none">
              <li><span class="h6 mr-3">Nom :</span><%= @item.title %></li>
              <li><span class="h6 mr-3">Catégorie :</span><%= @item.category.title %></li>
              <li><span class="h6 mr-3">Prix :</span><%= @item.price %>€</li>
              <li><span class="h6 mr-3">Dscription :</span><%= truncate(@item.description, :length => 150) %></li>
            </ul>
          <% end %>
        </div>
        <% active_item = false %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<br class="container">
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <h1 class="display-4-selection text-center">Editez votre profil</h1>

    <!-- Update Form -->
    <%= render 'update_form', user: @user %>

    <div class="text-center mt-5">
      <%= link_to 'Voir le profil', @user, class:"btn btn-primary mr-5" %>
      <%= link_to 'Retour Accueil', root_path, class:"btn btn-secondary" %>
    </div>

  </div>
</div>
<div class="col-3"></div>
</div>
</br>
</br>
</br>



</main>

app/views/users/show.html.erb
<h1 class="display-4-selection text-center my-5">Profil</h1>


  <div class="row justify-content-center">
    <div class="card border-primary mb-3" style="max-width: 18rem;">
      <div class="card-header">
        <p class="h4 text-center"><%= @user.first_name %> <%= @user.last_name %></p>
      </div>
      <div class="card-body text-primary">
        <h5 class="card-title text-center">Informations</h5>
        <p class="card-text text-center"><span class="h6 text-center">description:</span><br> <span class="ml-3 text-center"><%= @user.description %></span><br></p>
          <p class="card-text text-center"><span class="h6 text-center">email:</span><br> <span class="ml-3 text-center" ><%= @user.email %></span><br></p><br>
          <p class="card-text text-center"><span class="h6 text-center">Adresse:</span><br> <span class="text-center"><%= @user.address %><br></span><br></p>
          <p class="card-text text-center"><span class="h6 text-center">Code postal:</span><br> <span class="ml-3"><%= @user.zipcode %><br></span><br></p>

      </div>
    </div>
  </div>
  <br>
  <div class="text-center">
    <%= link_to "Editer mon profil", edit_user_path(current_user), class: "btn btn-primary mr-5" %>
    <%= link_to 'Retour Accueil', root_path, class:"btn btn-secondary" %>
    <br><br><br>

  </div>